### ISSUE TITLE
Filter user input

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#10]
In the current design, user input is not filtered. We want to make sure user inserts a URL only.

**Comment by sahil-ramagiri** [comment]
what urls do we support, can it be ftp or other protocols also do we support query params

**Comment by ksh168** [comment]
Hey Sahil, our primary target is for http and https links. But if possible, sure we can support other protocols as well. Addresses like "192.168.1.1" are also valid input. We just don't want user to input something random like "dfjgfvsbjfbwei" in URL field.

**Comment by sahil-ramagiri** [comment]
working on it!

**Comment by sahil-ramagiri** [comment]
updated pull request with screenshot #19
