### ISSUE TITLE
Deployment of website

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#15]
Currently the test website hosted locally and is only accessible on local system. Make changes to code such that it can be hosted on external service like AWS / Azure / heroku / pythonanywhere etc.

**Comment by Antsthebul** [comment]
Can i work on this?

**Comment by ksh168** [comment]
Hey @Antsthebul sure. But would you like to take up this whole issue or divide it it small parts? It's your choice. In case you choose the latter, create new issue for every part. I'll assign this to you.

**Comment by ksh168** [comment]
Also I suggest to use nginx to deploy the server for easy setup.
