### ISSUE TITLE
Stats dashboard for individual links

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#2]
Needs to show stats for each link to their individual links.
Let's say generated url is: `localhost/generatedurl`
Then if someone types:
`localhost/generatedurl-stats` or `localhost/generatedurl/stats`
It should show some basic stats like how many clicks on this link. It can be further enhanced using external analytics tools such as google analytics to find geographical region, device type and it's OS, time of day etc.
See an example [here](https://cutt.ly/bengaluru_real_estate_price_prediction-stats)

(This is a broad feature and will be divided into small parts)

**Comment by ksh168** [comment]
@sahil-ramagiri any suggestions on how to approach this issue?

**Comment by sahil-ramagiri** [comment]
Oh I just found a good resource
[https://realpython.com/python-web-applications-with-flask-part-ii/#deriving-data-from-visitors](https://realpython.com/python-web-applications-with-flask-part-ii/#deriving-data-from-visitors)

**Comment by ksh168** [comment]
Got it. Had to write a small function.
