### ISSUE TITLE
Make the current design compatible to support other protocols as well

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#20]
Current design supports "https://" and "http://". Make changes such that it is compatible to direct addresses such as "192.168.1.1" and other protocols like "ftp://" as well.

**Comment by sahil-ramagiri** [comment]
can I work on it?

**Comment by ksh168** [comment]
Yeah sure. I am hope you leave some issues for others also 😂. I'll assign this issue to you.

**Comment by sahil-ramagiri** [comment]
I did some research about possible protocols to support and the popular url shorteners only support http/s and ftp/s, all others are not supported for security reasons

**Comment by ksh168** [comment]
> I did some research about possible protocols to support and the popular url shorteners only support http/s and ftp/s, all others are not supported for security reasons

Applicable to direct addresses such as "192.168.1.1" too?

**Comment by sahil-ramagiri** [comment]
we already support direct addresses with protocols

**Comment by ksh168** [comment]
Ok. I understand. Continue with making it compatible with "ftp://"
