### ISSUE TITLE
Update README with screenshots of the new interface

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#27]
The interface is updated with an option for providing users personalized links. Update the screenshots in the README.

**Comment by ksh168** [comment]
@rutvikpadhiyar000 complete this issue here. I am assigning you.

**Comment by rutvikpadhiyar000** [comment]
hey should i remove current `link generated` example and add `custom link generated` example or add it as an extra example?

**Comment by rutvikpadhiyar000** [comment]
i mean should i have example of randomly generated URL or custom URL or both

**Comment by ksh168** [comment]
Yeah do both
