### ISSUE TITLE
Fix crash when optional fields are not supplied

### ISSUE THREAD

**Issue by sahil-ramagiri** [ksh168/smolink-url_shortener#28]
Also add error handling to routes

**Comment by ksh168** [comment]
Very well. I am assigning you.

**Comment by rutvikpadhiyar000** [comment]
there is another problem also if you try creating URL with same name it will give a database error instead of name not available i have fixed that and making pull request.

**Comment by ksh168** [comment]
Ok. Nice. I forgot to check that.
