### ISSUE TITLE
Custom option for making personalized URLs

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#3]
Allow users to create custom short url of their choice, instead of randomly generated strings. A URL like: `localhost/myportfolio` is descriptive and is likely to generate more clicks. (This issue is not regarding front end, that's a separate one)

**Comment by rutvikpadhiyar000** [comment]
I would like to take it

**Comment by ksh168** [comment]
Hey @rutvikpadhiyar000 sure. I'll assign this issue to you.

**Comment by ksh168** [comment]
Good Work!
