### ISSUE TITLE
Move url generation and handling custom urls code away from database model object

### ISSUE THREAD

**Issue by sahil-ramagiri** [ksh168/smolink-url_shortener#31]
Database model shouldn't handle the url generation part , it would be difficult later on to add other custom logic.

**Comment by ksh168** [comment]
Hey, can you explain a bit more about the issue and how it'll affect the project.

**Comment by sahil-ramagiri** [comment]
It would have made my last commit a little easier, can't think of any concrete examples now, but those db models are for defining schema, it would make a good abstraction to have the url generation seperate  so in case we can swap out different generation algos without affecting the db model.

**Comment by ksh168** [comment]
Ok. I understand. You can continue.
