### ISSUE TITLE
Rename the button on add_link page and update readme

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#36]
Currently the button is called "Short new URL". Change it to "Shorten another URL"

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by ksh168** [comment]
Hey @aditya28sarin , sure.

**Comment by 96RadhikaJadhav** [comment]
@ksh168  Can I also work on it?

**Comment by ksh168** [comment]
Hey @96RadhikaJadhav currently it's assigned to @aditya28sarin. If he doesn't update his PR in next 2hrs, the issue will be open to others again.
In the meantime, you can look at other issues or make yourself comfortable with the code.

**Comment by 96RadhikaJadhav** [comment]
@ksh168 Thanks for the update.

**Comment by ksh168** [comment]
@96RadhikaJadhav you can start working on it. Be sure to follow all guidelines.

**Comment by 96RadhikaJadhav** [comment]
@ksh168  Is it fine if I just rename the button in PR and update the screenshot in README.md ?

**Comment by ksh168** [comment]
Ok

**Comment by 96RadhikaJadhav** [comment]
@ksh168  I have created a PR. Could you please review it.
