### ISSUE TITLE
Make all the required fields display a red asterisk

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#39]
Don't do manually, use CSS.

**Comment by Siddharth1010** [comment]
Hey @ksh168 , could you assign this to me?

**Comment by ksh168** [comment]
Sure

**Comment by Siddharth1010** [comment]
@ksh168 There's only one required field right?

**Comment by ksh168** [comment]
Currently yes

**Comment by Siddharth1010** [comment]
So would you like me to create a separate "req" id for those fields or just add it to the default class "label"?

**Comment by ksh168** [comment]
What will be best for long term? Incase we add more fields of different input types in future.

**Comment by Siddharth1010** [comment]
I would suggest the former. All you would need to do is add id="req" to any label you add in the future. It will have a red asterisk.

**Comment by ksh168** [comment]
Ok. You can continue.
