### ISSUE TITLE
URL length validation

### ISSUE THREAD

**Issue by sahil-ramagiri** [ksh168/smolink-url_shortener#42]
1. We do not validate the length of original url and custom url, users can send urls of arbitrary character length. 
2. We dont validate custom end request, it can be even spaces. 
3. Sqlite doesn't enforce length of strings , so no errors are reported until now but others do, so it would break when we shift db.
4. We should discuss on fixing length of custom end, how large can be support

**Comment by ksh168** [comment]
Hey @sahil-ramagiri
* Regarding 1st point, the current limit of 512 characters is set manually by me. We can change it whenever is we want. 
* Regarding 2nd point, yes this is a valid point. We'll create a new issue for this.
* Regarding 4th point, will not fixing the length of custom end affect our model negatively?

We can discuss this further. Feel free to continue it here or at discord.

**Comment by sahil-ramagiri** [comment]
Limits are whatever we arbitrarily choose, but since it said in readme that we allow upto 512 characters but in reality we don't enforce it, so I raised that point.  
If we going to use sqlite only, then I see no problem, but technically it is a url shortener so just in a semantic sense it would be ok to set a limit.
Overall I am just nitpicking and there's no real problem.

**Comment by ksh168** [comment]
Hey, the points you raised are good. I appreciate it. We can start working on setting a limit on custom ending. I'll create an issue for it.
