### ISSUE TITLE
Current design doesn't validate custom end request, it can be even spaces

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#43]
This might cause some error with db

**Comment by ksh168** [comment]
will using python's `.strip()` method be of any help here?

**Comment by sahil-ramagiri** [comment]
we don't want spaces in between too, so replace is good, also we don't want all characters, only alphanumeric and hyphen

**Comment by ksh168** [comment]
@sahil-ramagiri why no spaces in between?
Also will allowing users to enter other characters cause any problem?

**Comment by sahil-ramagiri** [comment]
They will be encoded with percents, but it wouldn't be the url he requested right. Like he asked for `http://localhost:5000/hi!`
but we gave him `http://localhost:5000/hi%21`

**Comment by ksh168** [comment]
Hmm. Okay
