### ISSUE TITLE
set a limit on length of custom ending as well as original URL

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#44]
Currently there's no limit on how long the original URL and custom ending can be. Setting a limit of 512 characters for original URL and 64 characters for custom URL seems good enough right now.

**Comment by dheerajd5** [comment]
Can you assign this issue to me?

**Comment by ksh168** [comment]
Hey @dheerajd5 , sure.

**Comment by ksh168** [comment]
I have updated issue. Be sure to check that.
