### ISSUE TITLE
To make the generated short url a clickable link

### ISSUE THREAD

**Issue by ksh168** [ksh168/smolink-url_shortener#66]
The current generated short url is just plain text. it would be helpful to user if it's a clickable link

**Comment by guptag911** [comment]
Hey, won't be adding a button link "Go to URL" will be good?

**Comment by ksh168** [comment]
Hey @guptag911 sure, that sounds good too. Would you like to take this issue?

**Comment by guptag911** [comment]
**Sure**, I would like to work on this issue!

**Comment by ksh168** [comment]
Ok. I've assigned you.
