### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by viktor02** [ksh168/smolink-url_shortener#69]
```
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/etc/config.json'
```
Two questions:
In the readme it is not written anywhere where and how to create a config.
Why is the config created in /etc folder and not in the local folder?

**Comment by ksh168** [comment]
Hey @viktor02 . Apologies for the late reply.
Yes you're correct. README is missing on how to create a config file. Thank you for bringing that up.
I chose to make config.json in /etc folder, because usually OS config files are stored there. You can also store in local folder.
